sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1234

  redis:
    host: localhost
    port: 6379
    database: 0
  wechat:
    appid: wx666f0183da0876b2
    secret: 44854e2e23a1271638ac0dd0aac6e7a3
